version: '3.8'

services:
  # MongoDB với cấu hình thấp
  mongodb:
    image: mongo:7.0
    container_name: chatapp-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ChatApp2024
    command: mongod --wiredTigerCacheSizeGB 0.25 --quiet
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - chatapp-network
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 200M

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatapp-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - chatapp-network
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 300M

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatapp-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chatapp-network
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M

volumes:
  mongodb_data:

networks:
  chatapp-network:
    driver: bridge