version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: chatapp-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ChatApp2024SecurePass
      MONGO_INITDB_DATABASE: chatapp
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - chatapp-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatapp-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb://admin:ChatApp2024SecurePass@mongodb:27017/chatapp?authSource=admin
      JWT_SECRET: ChatApp2024SuperSecureJWTSecret-ChangeThis
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: "*"
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - chatapp-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatapp-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chatapp-network

volumes:
  mongodb_data:

networks:
  chatapp-network:
    driver: bridge